version: '3'

services:
  monster:
    build: './MonsterFetcher'
  item:
    build: './ItemFetcher'
  spell:
    build: './SpellFetcher'
  solr:
    build: "./solrSchemas"
    ports:
      - "8983:8983"
volumes:
  data: